"useclient";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Link from "next/link";

export const metadata = {
  title: "Flipmart",
  description: "Generated by Shwet Patel",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <div className="py-8">
          <Link href={"./123"}>go here</Link>
        </div>
        <Footer />
      </body>
    </html>
  );
}
